<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.1R6Kk1h' shared service.

return $this->privates['.service_locator.1R6Kk1h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\SystemeController::addprofil' => ['privates', '.service_locator.FA2Pq2J', 'get_ServiceLocator_FA2Pq2JService.php', true],
    'App\\Controller\\SystemeController::addsys' => ['privates', '.service_locator.6puk0Ru', 'get_ServiceLocator_6puk0RuService.php', true],
    'App\\Controller\\SystemeController:addprofil' => ['privates', '.service_locator.FA2Pq2J', 'get_ServiceLocator_FA2Pq2JService.php', true],
    'App\\Controller\\SystemeController:addsys' => ['privates', '.service_locator.6puk0Ru', 'get_ServiceLocator_6puk0RuService.php', true],
], [
    'App\\Controller\\SystemeController::addprofil' => '?',
    'App\\Controller\\SystemeController::addsys' => '?',
    'App\\Controller\\SystemeController:addprofil' => '?',
    'App\\Controller\\SystemeController:addsys' => '?',
]);
