<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXCjPYgc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXCjPYgc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXCjPYgc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXCjPYgc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXCjPYgc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XCjPYgc',
    'container.build_id' => '94790638',
    'container.build_time' => 1565805221,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXCjPYgc');
