<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXL3Yh3d\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXL3Yh3d/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXL3Yh3d.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXL3Yh3d\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXL3Yh3d\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XL3Yh3d',
    'container.build_id' => '5f10e462',
    'container.build_time' => 1565888577,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXL3Yh3d');
