<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerShvyS2k\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerShvyS2k/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerShvyS2k.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerShvyS2k\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerShvyS2k\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ShvyS2k',
    'container.build_id' => 'a39d1eb6',
    'container.build_time' => 1565807666,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerShvyS2k');
